### PR TITLE
Added conversion of eta xsi related values

### PR DESCRIPTION
**Pull request by bernhardmgruber**
Added conversion of the following elements:
* eta/xsi values -> eta/xsi iso lines
* elementUIDs to -> eta/xsi iso lines
* spar positions -> eta xsi rel height points

### CODE REVIEW

**Comment by rainman110** [comment]
@bernhardmgruber Very cool your contribution. Could you please just add function comments to
 - convertElementUidToEtaAndUid
 - convertEtaXsiRelHeightPoints

that describe the xml transformation that is performed? This is just xml transform, right? Do we (later) still need to recompute the coordinates (eta/xsi), since the coordinate system of the component segment has changed?

**Comment by bernhardmgruber** [comment]
I'll add comments tomorrow. Currently, the code just transforms the XML and yes, we still need a recomputation of the eta and xsi values for the new component segment space.

**Comment by rainman110** [comment]
@bernhardmgruber Can I merge?

The only drawback with the code right now is, that TiGL cannot open the wing structure anymore ;) (Which is still based on CPACS 2)

**Comment by bernhardmgruber** [comment]
you can merge it!

regarding the wing structure, it loads my test files just fine :S

**Comment by rainman110** [comment]
> regarding the wing structure, it loads my test files just fine :S

Yes, it loads it, but I get many warnings due to missing eta values.

**Comment by rainman110** [comment]
@bernhardmgruber BTW, you can directly work in this repository. I added you as a contributer.

**Comment by bernhardmgruber** [comment]
the errors when loading are probably because your spar positions haven't been updated to the lastest CPACS yet. spar positions now contain an etaXsiRelHeightPoint instead of eta and xsi values. this is correctly produced by script now, but TiGL3 cannot read this yet (our internal TiGL has already been updated).

**Pull request merged**
